### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by djordje200179** [ishrakland/Toast#14]
Will version for UWP be ever updated?

I'm getting an error:

`System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Plugin.Toast, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=DataGuard
  StackTrace:
   at DataGuard.App.RegisterTypes(IContainerRegistry containerRegistry)
   at Prism.PrismApplicationBase.Initialize()
   at Prism.PrismApplicationBase.InitializeInternal()
   at DataGuard.App..ctor(IPlatformInitializer initializer)
   at DataGuard.UWP.MainPage..ctor() in D:\Programiranje\NET\DataGuard\DataGuard.UWP\MainPage.xaml.cs:line 19`

**Comment by ishrakland** [comment]
You need xamarin forms 4.7.1351 and last Toast.plugin version 2.2.0

**Comment by walnut-co** [comment]
this is not working with xamarin forms 4.8.0.1560

**Comment by NightOwlCoder** [comment]
Yep, same here, just run the sample, made sure to update forms and got the same
```
System.IO.FileLoadException: Could not load file or assembly 'Plugin.Toast, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Sample.MainPage.Toast4Clicked(Object sender, EventArgs e)
   at Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked()
   at Xamarin.Forms.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementM```
